config/routes.rb
Rails.application.routes.draw do
  resources :latest_news_articles
  resources :video_gallery_groups
  resources :image_gallery_groups
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register_hidden'}
  resources :events
  resources :image_gallery_items
  resources :video_gallery_items
  resources :blogs
  get 'home', to: 'pages#home'
  get 'allevents', to: 'pages#events'
  get 'results', to: 'pages#results'
  get 'calendars', to: 'pages#calendars'
  get 'members', to: 'pages#members'
  get 'athletes', to: 'pages#athletes'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
  get 'gallery', to: 'pages#gallery'
  get 'gallery_group', to: 'pages#gallery_group'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/latest_news_article.rb
class LatestNewsArticle < ApplicationRecord
end

app/controllers/latest_news_articles_controller.rb
class LatestNewsArticlesController < ApplicationController
  before_action :set_latest_news_article, only: [:show, :edit, :update, :destroy]
  #access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  #petergate
  #access all: [:show, :index], user: {except: [:destroy]}, company_admin: :all
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  layout "scaffolds"

  # GET /latest_news_articles
  def index
    @latest_news_articles = LatestNewsArticle.all
  end

  # GET /latest_news_articles/1
  def show
  end

  # GET /latest_news_articles/new
  def new
    @latest_news_article = LatestNewsArticle.new
  end

  # GET /latest_news_articles/1/edit
  def edit
  end

  # POST /latest_news_articles
  def create
    @latest_news_article = LatestNewsArticle.new(latest_news_article_params)

    if @latest_news_article.save
      redirect_to latest_news_articles_url, notice: 'Latest news article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /latest_news_articles/1
  def update
    if @latest_news_article.update(latest_news_article_params)
      redirect_to latest_news_articles_url, notice: 'Latest news article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /latest_news_articles/1
  def destroy
    @latest_news_article.destroy
    redirect_to latest_news_articles_url, notice: 'Latest news article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_latest_news_article
      @latest_news_article = LatestNewsArticle.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def latest_news_article_params
      params.require(:latest_news_article).permit(:title, :body, :image_url)
    end
end

app/helpers/latest_news_articles_helper.rb
module LatestNewsArticlesHelper
end

app/views/latest_news_articles/_form.html.erb
<%= form_with(model: latest_news_article, local: true) do |form| %>
  <% if latest_news_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(latest_news_article.errors.count, "error") %> prohibited this latest_news_article from being saved:</h2>

      <ul>
      <% latest_news_article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group"> 
        <%= form.label :title %>
        <%= form.text_field :title, id: :latest_news_article_title, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group"> 
        <%= form.label :body %>
        <%= form.text_area :body, id: :latest_news_article_body, class: "form-control", required: "required", rows: 5 %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group"> 
        <%= form.label :image_url %>
        <%= form.text_field :image_url, id: :latest_news_article_image_url, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-4 btn-block" %>
  </div>
<% end %> 

app/views/latest_news_articles/edit.html.erb
<h1>Editing Latest News Article</h1>

<%= render 'form', latest_news_article: @latest_news_article %>

<%= link_to 'Show', @latest_news_article %> |
<%= link_to 'Back', latest_news_articles_path %>

app/views/latest_news_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Latest News Articles</h1>

<%= link_to 'New Latest News Article', new_latest_news_article_path, class: "btn btn-primary" %>

<table id="example" class="display blog-table" style="width:100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image url</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @latest_news_articles.each do |latest_news_article| %>
      <tr>
        <td><%= latest_news_article.title %></td>
        <td><%=raw latest_news_article.body %></td>
        <td><%= latest_news_article.image_url %></td>
        <td><%= link_to 'Edit', edit_latest_news_article_path(latest_news_article) %></td>
        <td><%= link_to 'Delete', latest_news_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/latest_news_articles/new.html.erb
<h1>New Latest News Article</h1>

<%= render 'form', latest_news_article: @latest_news_article %>

<%= link_to 'Back', latest_news_articles_path %>

app/views/latest_news_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @latest_news_article.title %>
</p>
<hr> 

<p>
  <strong>Body:</strong>
  <%= @latest_news_article.body %>
</p>
<hr> 

<p>
  <strong>Image url:</strong>
  <%= @latest_news_article.image_url %>
</p>

<%= link_to 'Edit', edit_latest_news_article_path(@latest_news_article) %> |
<%= link_to 'Back', latest_news_articles_path %>