config/routes.rb
Rails.application.routes.draw do
  resources :latest_news_articles
  resources :video_gallery_groups
  resources :image_gallery_groups
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register_hidden'}
  resources :events
  resources :image_gallery_items
  resources :video_gallery_items
  resources :blogs
  get 'home', to: 'pages#home'
  get 'allevents', to: 'pages#events'
  get 'results', to: 'pages#results'
  get 'calendars', to: 'pages#calendars'
  get 'members', to: 'pages#members'
  get 'athletes', to: 'pages#athletes'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
  get 'gallery', to: 'pages#gallery'
  get 'gallery_group', to: 'pages#gallery_group'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image_gallery_group.rb
class ImageGalleryGroup < ApplicationRecord
	
end

app/controllers/image_gallery_groups_controller.rb
class ImageGalleryGroupsController < ApplicationController
  before_action :set_image_gallery_group, only: [:show, :edit, :update, :destroy]
  #access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  #petergate
  #access all: [:show, :index], user: {except: [:destroy]}, company_admin: :all
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  layout "scaffolds"

  # GET /image_gallery_groups
  def index
    @image_gallery_groups = ImageGalleryGroup.all
  end

  # GET /image_gallery_groups/1
  def show
  end

  # GET /image_gallery_groups/new
  def new
    @image_gallery_group = ImageGalleryGroup.new
  end

  # GET /image_gallery_groups/1/edit
  def edit
  end

  # POST /image_gallery_groups
  def create
    @image_gallery_group = ImageGalleryGroup.new(image_gallery_group_params)

    if @image_gallery_group.save
      redirect_to image_gallery_groups_url, notice: 'Image gallery group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /image_gallery_groups/1
  def update
    if @image_gallery_group.update(image_gallery_group_params)
      redirect_to image_gallery_groups_url, notice: 'Image gallery group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /image_gallery_groups/1
  def destroy
    @image_gallery_group.destroy
    redirect_to image_gallery_groups_url, notice: 'Image gallery group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_gallery_group
      @image_gallery_group = ImageGalleryGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def image_gallery_group_params
      params.require(:image_gallery_group).permit(:title, :body)
    end
end

app/helpers/image_gallery_groups_helper.rb
module ImageGalleryGroupsHelper
end

app/views/image_gallery_groups/_form.html.erb
<%= form_with(model: image_gallery_group, local: true) do |form| %>
  <% if image_gallery_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_gallery_group.errors.count, "error") %> prohibited this image_gallery_group from being saved:</h2>

      <ul>
      <% image_gallery_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group"> 
        <%= form.label :title %>
        <%= form.text_field :title, id: :image_gallery_group_title, class: "form-control", required: "required" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group"> 
        <%= form.label :body %>
        <%= form.text_area :body, id: :image_gallery_group_body, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="actions">
        <%= form.submit class: "btn btn-4 btn-block" %> 
      </div>
    </div>
  </div>

<% end %>

app/views/image_gallery_groups/edit.html.erb
<h1>Editing Image Gallery Group</h1>

<%= render 'form', image_gallery_group: @image_gallery_group %>

<%= link_to 'Show', @image_gallery_group %> |
<%= link_to 'Back', image_gallery_groups_path %>

app/views/image_gallery_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Gallery Groups</h1>

<%= link_to 'New Image Gallery Group', new_image_gallery_group_path, class: "btn btn-primary" %>

<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @image_gallery_groups.each do |image_gallery_group| %>
      <tr>
        <td><%= image_gallery_group.title %></td>
        <td><%= image_gallery_group.body %></td>
        <td><%= link_to 'Edit', edit_image_gallery_group_path(image_gallery_group) %></td>
        <td><%= link_to 'Destroy', image_gallery_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 

app/views/image_gallery_groups/new.html.erb
<h1>New Image Gallery Group</h1>

<%= render 'form', image_gallery_group: @image_gallery_group %>

<%= link_to 'Back', image_gallery_groups_path %>

app/views/image_gallery_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image_gallery_group.title %>
</p>
<hr> 

<p>
  <strong>Body:</strong>
  <%= @image_gallery_group.body %>
</p>

<%= link_to 'Edit', edit_image_gallery_group_path(@image_gallery_group) %> |
<%= link_to 'Back', image_gallery_groups_path %>