config/routes.rb
Rails.application.routes.draw do
  resources :latest_news_articles
  resources :video_gallery_groups
  resources :image_gallery_groups
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register_hidden'}
  resources :events
  resources :image_gallery_items
  resources :video_gallery_items
  resources :blogs
  get 'home', to: 'pages#home'
  get 'allevents', to: 'pages#events'
  get 'results', to: 'pages#results'
  get 'calendars', to: 'pages#calendars'
  get 'members', to: 'pages#members'
  get 'athletes', to: 'pages#athletes'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
  get 'gallery', to: 'pages#gallery'
  get 'gallery_group', to: 'pages#gallery_group'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image_gallery_item.rb
class ImageGalleryItem < ApplicationRecord
	
end

app/controllers/image_gallery_items_controller.rb
class ImageGalleryItemsController < ApplicationController
  before_action :set_image_gallery_item, only: [:show, :edit, :update, :destroy]

  #petergate
  #access all: [:show, :index], user: {except: [:destroy]}, company_admin: :all
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  layout "scaffolds"

  # GET /image_gallery_items
  # GET /image_gallery_items.json
  def index
    @image_gallery_items = ImageGalleryItem.all
    @gallerygroups = ImageGalleryGroup.all
  end

  # GET /image_gallery_items/1
  # GET /image_gallery_items/1.json
  def show
  end

  # GET /image_gallery_items/new
  def new
    @image_gallery_item = ImageGalleryItem.new
    @gallerygroups = ImageGalleryGroup.all
  end

  # GET /image_gallery_items/1/edit
  def edit
    @gallerygroups = ImageGalleryGroup.all
  end

  # POST /image_gallery_items
  # POST /image_gallery_items.json
  def create
    @image_gallery_item = ImageGalleryItem.new(image_gallery_item_params)

    respond_to do |format|
      if @image_gallery_item.save
        format.html { redirect_to image_gallery_items_url, notice: 'Image gallery item was successfully created.' }
        format.json { render :show, status: :created, location: @image_gallery_item }
      else
        format.html { render :new }
        format.json { render json: @image_gallery_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_gallery_items/1
  # PATCH/PUT /image_gallery_items/1.json
  def update
    respond_to do |format|
      if @image_gallery_item.update(image_gallery_item_params)
        format.html { redirect_to image_gallery_items_url, notice: 'Image gallery item was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_gallery_item }
      else
        format.html { render :edit }
        format.json { render json: @image_gallery_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_gallery_items/1
  # DELETE /image_gallery_items/1.json
  def destroy
    @image_gallery_item.destroy
    respond_to do |format|
      format.html { redirect_to image_gallery_items_url, notice: 'Image gallery item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_gallery_item
      @image_gallery_item = ImageGalleryItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_gallery_item_params
      params.require(:image_gallery_item).permit(:title, :body, :image_url, :image_gallery_name)
    end
end

app/helpers/image_gallery_items_helper.rb
module ImageGalleryItemsHelper
end

app/views/image_gallery_items/_form.html.erb
<%= form_with(model: image_gallery_item, local: true) do |form| %>
  <% if image_gallery_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image_gallery_item.errors.count, "error") %> prohibited this image_gallery_item from being saved:</h2>

      <ul>
      <% image_gallery_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :image_gallery_item_title, class: "form-control", required: "required" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group">
        <%= form.label :body %>
        <%= form.text_area :body, id: :image_gallery_item_body, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group">
        <%= form.label :image_url %>
        <%= form.text_field :image_url, id: :image_gallery_item_image_url, class: "form-control", required: "required" %>
      </div>
    </div>
  </div>

  <% groupid = image_gallery_item[:image_gallery_name].to_i  %>

  <div class="row">
    <div class="col-sm-12">
      <div class="field form-group">
        <%= form.label :image_gallery_name %>
        <select name="image_gallery_item[image_gallery_name]" id="<%= :image_gallery_item_image_gallery_name %>" class="form-control">
          <% @gallerygroups.each do |groupname| %>
            <option <%= groupid == groupname[:id] ? "selected=\"selected\"" : "" %> value="<%= groupname[:id] %>"><%= groupname[:title] %></option>
          <% end %>
        </select>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="actions">
        <%= form.submit class: "btn btn-4 btn-block" %>
      </div>
    </div>
  </div>
  
<% end %>

app/views/image_gallery_items/edit.html.erb
<h1>Editing Image Gallery Item</h1>

<%= render 'form', image_gallery_item: @image_gallery_item %>

<%= link_to 'Show', @image_gallery_item %> |
<%= link_to 'Back', image_gallery_items_path %>

app/views/image_gallery_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Image Gallery Items</h1>

<%= link_to 'New Image Gallery Item', new_image_gallery_item_path, class: "btn btn-primary" %>

<table id="example" class="display" style="width:100%">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image url</th>
      <th>Image gallery name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @image_gallery_items.each do |image_gallery_item| %>
      <tr>
        <td><%= image_gallery_item.title %></td>
        <td><%= image_gallery_item.body %></td>
        <td><%= image_gallery_item.image_url %></td>
        <td><%= @gallerygroups.find(image_gallery_item.image_gallery_name.to_i)[:title] %></td>
        <td><%= link_to 'Edit', edit_image_gallery_item_path(image_gallery_item) %></td>
        <td><%= link_to 'Destroy', image_gallery_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 

app/views/image_gallery_items/new.html.erb
<h1>New Image Gallery Item</h1>

<%= render 'form', image_gallery_item: @image_gallery_item %>

<%= link_to 'Back', image_gallery_items_path %>

app/views/image_gallery_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image_gallery_item.title %>
</p>
<hr>

<p>
  <strong>Body:</strong>
  <%= @image_gallery_item.body %>
</p>
<hr>

<p>
  <strong>Image url:</strong>
  <%= @image_gallery_item.image_url %>
</p>
<hr>

<p>
  <strong>Image gallery name:</strong>
  <%= @image_gallery_item.image_gallery_name %>
</p>

<%= link_to 'Edit', edit_image_gallery_item_path(@image_gallery_item) %> |
<%= link_to 'Back', image_gallery_items_path %>