config/routes.rb
Rails.application.routes.draw do
  resources :latest_news_articles
  resources :video_gallery_groups
  resources :image_gallery_groups
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register_hidden'}
  resources :events
  resources :image_gallery_items
  resources :video_gallery_items
  resources :blogs
  get 'home', to: 'pages#home'
  get 'allevents', to: 'pages#events'
  get 'results', to: 'pages#results'
  get 'calendars', to: 'pages#calendars'
  get 'members', to: 'pages#members'
  get 'athletes', to: 'pages#athletes'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#contact'
  get 'gallery', to: 'pages#gallery'
  get 'gallery_group', to: 'pages#gallery_group'

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- for search engine description -->
	<meta name="description" content="Uganda Swimming Federation">
	
	<title><%= @page_title %></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<!-- Datatables -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
</head>

<body>

	<header>
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
			<div class="container">
				<%= link_to image_tag("logo.png", alt: "Logo"), home_path, class: "navbar-brand" %>
				
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/home" || request.env['PATH_INFO'] == "/" %>">
							<%= link_to fa_icon("home"), home_path, class: "nav-link", title: "Home" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/events" %>">
							<%= link_to "Events", allevents_path, class: "nav-link" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/results" %>">
							<%= link_to "Results", results_path, class: "nav-link" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/calendars" %>">
							<%= link_to "Calendars", calendars_path, class: "nav-link" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/members" %>">
							<%= link_to "Members", members_path, class: "nav-link" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/athletes" %>">
							<%= link_to "Athletes", athletes_path, class: "nav-link" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/about" %>">
							<%= link_to "About", about_path, class: "nav-link" %>
						</li>
						<li class="nav-item <%= "active".html_safe if request.env['PATH_INFO'] == "/contact" %>">
							<%= link_to "Contact", contact_path, class: "nav-link" %>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>


	<main role="main">

		<% if !notice.nil? || !alert.nil? %>
			<%= tag.div class: "alert alert-success alert-dismissible centered alert-msg" do %>
				<button type="button" class="close" data-dismiss="alert">&times;</button>
		  		<%= notice %>
		  		<%= alert %>
			<% end %>
		<% end %>

		<%= yield %>

		<div class="container-fluid large-footer largepadding">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div><strong><small>NAVIGATION</small></strong></div>
						<div>&bull; <%= link_to "Home", home_path %></div>
						<div>&bull; <%= link_to "Events", allevents_path %></div>
						<div>&bull; <%= link_to "Results", results_path %></div>
						<div>&bull; <%= link_to "Calendars", calendars_path %></div>
						<div>&bull; <%= link_to "Members", members_path %></div>
						<div>&bull; <%= link_to "Athletes", athletes_path %></div>
						<div>&bull; <%= link_to "About", about_path %></div>
						<div>&bull; <%= link_to "Contact", contact_path %></div>
					</div>
					<div class="col-sm-8">
						<div><strong><small>EVENTS</small></strong></div>
						<% @events.limit(4).each do |event_entry| %>
							<div class="footer-event">
								&bull; <%= event_entry.title %>
								<div class="footer-event-details">
									<%= fa_icon "clock-o" %> <%= event_entry.event_date.strftime("%d %b %Y") %>
									<%= fa_icon "map-marker" %> <%= event_entry.event_location %>
								</div>
							</div>
						<% end %>
					</div>
					<div class="col-sm-2">
						<div><strong><small>SOCIAL MEDIA</small></strong></div>
						<%= link_to fa_icon("facebook-square"), "https://www.facebook.com/UgandaSwimmingFederation/", target: "_blank" %>
						<%= link_to fa_icon("twitter-square"), "https://twitter.com/UgandaSwimming", target: "_blank" %>
					</div>
				</div>
			</div>
		</div>
	</main>

	<footer style="margin: 0 5px;">
		&copy; <%= Time.new.year %> All Rights Reserved. Uganda Swimming Federation | 
		Developed by: 
		<%= link_to "The iVii Development Team", "http://iviidev.info", target: "_blank" %> 		
		<% if current_user %>
			<%= link_to " | Log out", destroy_user_session_path, method: :delete %>
		<% end %>
	</footer>
	
</body> 
</html>

app/views/layouts/scaffolds.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- for search engine description -->
	<meta name="description" content="Uganda Swimming Federation">
	
	<title><%= @page_title %></title>
	
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'scaffolds' %>
	
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<!-- Datatables -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
	
</head>

<body>
	<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
		<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Dashboard</a>
		<ul class="navbar-nav px-3">
			<li class="nav-item text-nowrap">
				<% if current_user %>
					<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "signoutlink" %>
				<% else %>	
					<% controller.redirect_to home_path %>
				<% end %>
			</li>
		</ul>
	</nav>

	<div class="container-fluid">
		<div class="row">
			<nav class="col-md-2 d-none d-md-block bg-light sidebar">
				<div class="sidebar-sticky">
					<ul class="nav flex-column">
						<li class="nav-item">
							<%= link_to "Latest News", latest_news_articles_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "Blogs", blogs_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "Events", events_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "Image Gallery", image_gallery_items_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "> Image Gallery Groups", image_gallery_groups_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "Video Gallery", video_gallery_items_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "> Video Gallery Groups", video_gallery_groups_path, class: "nav-link" %>
						</li>						
						<li class="nav-item">
							<%= link_to "USF HOME", home_path, class: "nav-link" %>
						</li>
					</ul>
				</div>
			</nav>

			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4 padding-bottom">
				
				<%= yield %>

			</main>
		</div>
	</div>

	<!-- Datatables -->
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $('#example').DataTable();
		} );
	</script>

</body>
</html>